language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black . 

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-147551946776"

