language: python

python:
  - 3.7

install:
  - pip install importlib-metadata --upgrade
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black . 
  - flake8 .
  - coverage run --source='.' manage.py test polls

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-147551946776"
  on:
    branch: main
